# Generated by Django 4.1.2 on 2022-10-20 14:34

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('nEmpresa', models.CharField(max_length=60, unique=True, verbose_name='Razon Social')),
                ('clase_rif', models.CharField(choices=[('V', 'Natural de la República Bolivariana de Venezuela'), ('J', 'Personal Jurídica'), ('G', 'Ente Gubernamental'), ('E', 'Extranjero con residencia en Venezuela'), ('P', 'Agente Registrado Con Pasaporte')], default='G', max_length=1, verbose_name='Estatus del Empleado')),
                ('rif', models.CharField(max_length=10, unique=True, verbose_name='RIF')),
                ('naCronimo', models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Acronimo')),
                ('logoImg', models.ImageField(blank=True, null=True, upload_to='empresa/logo', verbose_name='LOGOTIPO')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre y Apellido')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Numero de Cedula')),
            ],
            options={
                'verbose_name': 'Registro Visitante',
                'verbose_name_plural': 'Registro de los visitantes',
            },
        ),
        migrations.CreateModel(
            name='Departaments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('nOficina', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Oficina a Visitar')),
                ('extTelefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None)),
                ('Nempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgv.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos ',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('nCargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('nGerente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Encargado')),
                ('nDepartamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgv.departaments', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fEntrada', models.DateTimeField(auto_now=True, verbose_name='Hora')),
                ('equipos', models.CharField(choices=[('Laptop', 'Laptop'), ('videoBeam', 'videoBeam'), ('Speaker', 'Speaker'), ('Ninguno', 'Ninguno')], default='Ninguno', max_length=10, verbose_name='Equipos Tecnologicos')),
                ('marca', models.CharField(max_length=40, verbose_name='Marca')),
                ('serial', models.CharField(max_length=50, verbose_name='Serial Code')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgv.empresa')),
                ('nDepartamentos', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='nOficina', chained_model_field='nDepartamentos_id', on_delete=django.db.models.deletion.CASCADE, to='sgv.cargo')),
                ('nInvitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgv.invitado')),
                ('nOficina', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='empresa', chained_model_field='Nempresa_id', on_delete=django.db.models.deletion.CASCADE, to='sgv.departaments')),
            ],
            options={
                'verbose_name': 'Acceso a la Sede',
                'verbose_name_plural': 'Acceso a la Sede',
            },
        ),
    ]
