# Generated by Django 4.1.2 on 2022-10-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('nEmbresa', models.CharField(max_length=60, unique=True, verbose_name='Razon Social')),
                ('clase_rif', models.CharField(choices=[('V', 'Natural de la República Bolivariana de Venezuela'), ('J', 'Perso(nal Jurídica'), ('G', 'Ente Gubernamental'), ('E', 'Extranjero con residencia en Venezuela'), ('P', 'Agente Registrado Con Pasaporte')], default='V', max_length=1, verbose_name='Estatus del Empleado')),
                ('rif', models.CharField(max_length=10, unique=True, verbose_name='RIF')),
                ('logoImg', models.ImageField(blank=True, null=True, upload_to='empresa/logo', verbose_name='LOGOTIPO')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Departaments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('nOficina', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Oficina a Visitar')),
                ('extTelefono', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Numero de Ext.')),
                ('Nempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgv.empresa')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos ',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('nCargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('nDepartamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgv.departaments')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
