# Generated by Django 4.1.2 on 2022-10-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='naCronimo',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Acronimo'),
        ),
    ]
