# Generated by Django 4.1.2 on 2022-10-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgv', '0004_alter_departaments_exttelefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre y Apellido')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Numero de Cedula')),
            ],
            options={
                'verbose_name': 'Registro Visitante',
                'verbose_name_plural': 'Registro de los visitantes',
            },
        ),
    ]
