# Generated by Django 4.1.2 on 2022-10-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgv', '0005_invitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('equipos', models.CharField(choices=[('lap', 'Laptop'), ('vb', 'videoBeam'), ('sp', 'Speaker'), ('na', 'Ninguno')], default='na', max_length=3, verbose_name='Equipos Tecnologicos')),
                ('marca', models.CharField(max_length=40, verbose_name='Marca')),
                ('serial', models.CharField(max_length=50, verbose_name='Serial Code')),
            ],
            options={
                'verbose_name': 'Equipos Tecnologico',
                'verbose_name_plural': 'Equipos Tecnologicos',
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='nGerente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Encargado'),
        ),
    ]
