# Generated by Django 4.1.2 on 2022-10-19 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgv', '0006_herramientas_cargo_ngerente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nDepartamentos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgv.departaments', verbose_name='Departamento'),
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('fEntrada', models.TimeField(auto_now=True, verbose_name='Hora')),
                ('FSalida', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgv.invitado')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgv.herramientas')),
                ('nCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgv.cargo')),
                ('nDepartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgv.departaments')),
            ],
            options={
                'verbose_name': 'Acceso a la Sede',
                'verbose_name_plural': 'Acceso a la Sede',
            },
        ),
    ]
